[package]
name = "tcore"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version="1.20.1", features=["full"]}
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.5.2" }
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.5.2" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.4", features = ["api-all"] }
thiserror = "1.0.31"
include_dir = "0.7.2"
data-encoding = "2.3.2"
ring = "0.16.20"
prisma={path="./prisma"}
ts-rs={version="6.2", features=["chrono-impl", "uuid-impl", "serde-compat"]}
rand = "0.8.5"
