[package]
name = "tcore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prisma-client-rust = { workspace = true, default-features = false, features = [
    "sqlite",
    "rspc",
    "sqlite-create-many",
    "migrations"
] }
tauri = { version = "1.0.5", features = ["api-all"] }
prisma={path="../../prisma"}
rspc = { workspace = true, features = [
    "uuid",
    "tauri",
    "chrono",
    "tracing",
] }
dirs = "4.0.0"
