[package]
name = "rust-core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio={version="1.0", features=["full"]}
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.2.0", features = [] }
anyhow = "1.0.66"
dirs="4.0.0"
rspc= {workspace=true, features= ["tauri"] }
